### ISSUE TITLE
Error message to vague 

### ISSUE THREAD

**Issue by CristianFodor** [multiversx/mx-sdk-dapp#724]
https://github.com/multiversx/mx-sdk-dapp/blob/f501fbbb2781b6b0c2147a89246808c95de43cfc/src/apiCalls/accounts/getAccountFromApi.ts#L17

Hello, 

Some users are not able to connect with xPortal app when using the app from mobile phone browser. All that I can see as an error in mobile browser is this custom error message. Can this message error have more information attached to it ? It will help the debugging a lot.

**Comment by radumojic** [comment]
This was answered and fixed on a different channel.

The error is unrelated to the signing provider, and the error description states the encountered issue on this function only. Since there's no extra processing on the api response, the expected breaking point here is the api call per se.

The original answer that helped on the different channel was:

Hello, this error is logged when there is an issue while fetching the account details from the public api, it might have been a temporary hiccup as the status dashboard shows no issues recently: https://status.multiversx.com/

If a temporary connection issue/rate limit is out of question, a possibility is that the request was cancelled by the app due to some state change.

Sometimes issues with effects/hooks are more proeminent with React <StrictMode> as components or hooks will quickly re-render and some race conditions might trigger invalid states.
